JS testing is called from correct dir with correct args
...and with correct branch.

fixes:
```
TypeError: imports.newlinesToHTMLBreaks(...).toBe is not a function
```

fixes
```
ENOENT: no such file or directory, open '/tmp/build/14fdeea7/package.js
```

fixes
```
Usage: npm <command>
```

Signed-off-by: Brian Cunnie <brian.cunnie@gmail.com>