IBM Commands have correct paths
- commands within a Docker container use `/blabbertabber`
  regular commands use `/var/blabbertabber
- `bash -c` requires ONE argument, not many
  (e.g. `exec.Command("bash", "-c", "echo 'I love you' > /tmp/j.txt")
  (args past ONE become positional params, i.e. $1, $2, etc...)
- `ibmjson` has absolute pathname
- `wav_file_list.txt` has correct pathnames within

fixes:
```
panic: exec: "ibmjson": executable file not found in $PATH
```

fixes:
```
exceptions.IOError: [Errno 2] No such file or directory: '/var/blabbertabber/soundFiles/8d153662-93cd-4a63-9821-d6cf76d14e45/meeting.wav'
```