CI: Bump `golang-ginkgo` Dockerfile
- it has been two years since last bump
- incorporates Ginkgo's new `When()` directive, which is much more
natural than `Describe()` or `Context()`
- `yarn` replaces `npm`
- follow these instructions to install nodejs:
<https://nodejs.org/en/download/package-manager>
- ...which, in turn, have instructions for installing `yarn`
- ...which has a slightly different syntax for installing `jest`

fixes <https://ci.nono.io/teams/main/pipelines/u2date/jobs/integration/builds/24>:
```
u2date/u2date_test.go:40:2: undefined: When
```